// Generated by BuildPilot from the validated call transcript for Al Khaima.
// Do not hand-edit business data here across rebuilds — update the source
// requirements and regenerate instead. See src/types/site-config.ts (starter
// template) for the full SiteConfig shape (cinematic or plain variant) and
// docs/DEVIN_3D_WEBSITE_SPEC.md for how each field is used.
import type { SiteConfig } from "./types/site-config";

export const siteConfig: SiteConfig = {
  "variant": "cinematic",
  "businessName": "Al Khaima",
  "purpose": "Levantine grill restaurant in Al Quoz, Dubai offering grills, mezze, fresh juices, and catering.",
  "targetAudience": "Families in the evenings and office workers for lunch; delivery customers via apps.",
  "contact": {},
  "palette": {
    "background": "#1A0D0A",
    "surface": "#2B1E14",
    "text": "#F8EFE7",
    "muted": "#CBAA8A",
    "accent": "#D97A2B",
    "accentHover": "#FFB347"
  },
  "enquirySection": {
    "id": "enquiry",
    "eyebrow": "Let’s plan your moment",
    "heading": "Enquiries & Catering",
    "body": "We cater for events and offices with a Levantine touch. Tell us what you’re imagining and we’ll tailor a plan.",
    "submitLabel": "Send enquiry",
    "enquiryTypes": [
      "General Enquiry",
      "Catering Request",
      "Delivery & Availability",
      "Menu Customisation"
    ],
    "disconnectedMessage": "Form submission is not connected yet.",
    "consentLabel": "I consent to be contacted regarding this enquiry."
  },
  "navigation": [
    {
      "label": "Highlights",
      "href": "#products"
    },
    {
      "label": "Enquire",
      "href": "#enquiry"
    }
  ],
  "assets": {
    "collection": "restuarant",
    "root": "/assets/restuarant",
    "framesDirectory": "/assets/restuarant/frames",
    "productsDirectory": "/assets/restuarant/products"
  },
  "hero": {
    "directory": "/assets/restuarant/frames",
    "poster": "/assets/restuarant/frames/ezgif-frame-001.jpg",
    "filePrefix": "ezgif-frame-",
    "fileExtension": "jpg",
    "framePadding": 3,
    "firstFrame": 1,
    "frameCount": 300,
    "width": 1920,
    "height": 1080,
    "scrollHeightVh": 600,
    "maxDevicePixelRatio": 2,
    "maxCachedFrames": 48,
    "loadConcurrency": 6,
    "narrowViewportBreakpoint": 768,
    "focalPoint": {
      "wide": {
        "x": 0.5,
        "y": 0.5
      },
      "narrow": {
        "x": 0.62,
        "y": 0.5
      }
    },
    "chapters": [
      {
        "id": "opening",
        "from": 0,
        "to": 0.24,
        "align": "left",
        "showScrollCue": true,
        "eyebrow": "About Al Khaima",
        "heading": "Levantine grill, warm hospitality in Al Quoz",
        "body": "Al Khaima is a Levantine grill restaurant in Al Quoz, Dubai offering grills, mezze, fresh juices, and catering."
      },
      {
        "id": "mid",
        "from": 0.34,
        "to": 0.6,
        "align": "right",
        "eyebrow": "What makes us different",
        "heading": "Sharing plates, Halal-certified warmth",
        "body": "We welcome families in the evenings and office teams at lunch, with Halal-certified meals and a menu built for sharing."
      },
      {
        "id": "closing",
        "from": 0.72,
        "to": 1,
        "align": "left",
        "eyebrow": "Ready to dine?",
        "heading": "Order now or explore catering",
        "body": "Open daily from noon until midnight. Tap Order Now to begin your Levantine experience, or view our menu and catering options.",
        "primaryCta": {
          "label": "Order Now",
          "href": "#enquiry"
        },
        "secondaryCta": {
          "label": "View Menu",
          "href": "#products"
        }
      }
    ]
  },
  "productsSection": {
    "id": "products",
    "eyebrow": "Our signature offerings",
    "heading": "Curated plates for every table",
    "body": "A selection of passionate Levantine dishes designed for sharing and delight.",
    "scrollHeightVh": 500,
    "imageAspectRatio": "1:1",
    "items": [
      {
        "category": "Vegetarian",
        "name": "Signature Vegetarian Platter",
        "description": "A vibrant, share-friendly assortment of Levantine vegetarian bites, crafted for groups and celebrations.",
        "image": "signature-vegetarian-platter.jpg"
      },
      {
        "category": "Mezze",
        "name": "Fresh Mezze",
        "description": "A lively selection of small plates that captures Levantine brightness and depth, prepared fresh for your table.",
        "image": "fresh-mezze.jpg"
      },
      {
        "category": "Vegetarian Sides",
        "name": "Charcoal Roasted Cauliflower",
        "description": "Smoky florets roasted over charcoal, finished with herbs and a bright touch of lemon.",
        "image": "charcoal-roasted-cauliflower.jpg"
      },
      {
        "category": "Beverages",
        "name": "Fresh Juices",
        "description": "Bright, refreshing juices to lift every meal and accompany your Levantine favorites.",
        "image": "fresh-juices.jpg"
      }
    ]
  }
} satisfies SiteConfig;
